version: 2
jobs:
  build:
    working_directory: ~/cuscuzjobs
#    docker:
#      - image: circleci/python:3.6.4
#        environment:
#          PIPENV_VENV_IN_PROJECT: true
#          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
#      - image: circleci/postgres:9.6.2
#        environment:
#          POSTGRES_USER: root
#          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
#      - run:
#          name: Setting DataBase
#          command: |
#            pipenv run "make setup"
#            pipenv run "make migra n=users_auth"
#            pipenv run "make migra n=company"
#            pipenv run "make migra n=job"

#      - run:
#          name: Tests
#          command: |
#            pipenv run "python manage.py test"

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          destination: tr1
